# -*- coding: utf-8 -*-
"""Zomato Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DaQzqsUE42Oof9G6zD6uDlATyzjQpyb8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the downloaded CSV file into a pandas DataFrame
df = pd.read_csv('/Zomato-data-.csv')

# Display the first 5 rows of the DataFrame
display(df.head())

def handleRate(value):
  value = str(value).split('/')
  value = value[0]
  return float(value)
df['rate'] = df['rate'].apply(handleRate)
print(df.head())

df.info()

print(df.isnull().sum())

sns.countplot(x=df['listed_in(type)'])
plt.xlabel("Types of restaurant")

grouped_data = df.groupby('listed_in(type)')['votes'].sum()
result = pd.DataFrame({'votes':grouped_data})
plt.plot(result,c='green',marker='o')
plt.xlabel("Types of restaurant")
plt.ylabel("Votes")

max_votes = df['votes'].max()
restaurant_with_max_votes = df[df['votes'] == max_votes]
print(restaurant_with_max_votes)

sns.countplot(x=df['online_order'])
#

plt.hist(df['rate'],bins=5)
plt.title('Ratings Distribution')
plt.show()



"""# Zomato Data Analysis

## Project Description
This project involves analyzing Zomato restaurant data to understand various aspects of restaurant operations and customer preferences. The analysis focuses on understanding restaurant ratings, votes, online order availability, and table booking preferences.

## Dataset
The dataset used in this analysis is `Zomato-data-.csv`, which contains information about restaurants, including their names, online order availability, table booking options, ratings, number of votes, approximate cost for two people, and listed restaurant types.

## Analysis Goals
1.  **Explore Basic Data Information**: Understand the structure, data types, and identify any missing values in the dataset.
2.  **Analyze Ratings Distribution**: Visualize the distribution of restaurant ratings.
3.  **Identify Popular Restaurant Types**: Determine which restaurant types receive the most votes.
4.  **Analyze Online Order Preferences by Restaurant Type**: Visualize the distribution of online order availability across different restaurant types.
5.  **Analyze Table Booking Preferences by Restaurant Type**: Visualize the distribution of table booking availability across different restaurant types.

## How to Run the Code
This code is designed to be run in a Google Colaboratory environment.

### Prerequisites
*   Google Colab account.
*   Access to the `Zomato-data-.csv` dataset. (Note: Ensure the CSV file is accessible, either by uploading it to your Colab environment or by providing a publicly accessible Google Drive link).

### Steps
1.  **Open in Google Colab**: Open the `.ipynb` notebook file in Google Colab.
2.  **Run Cells Sequentially**: Execute the code cells one by one. The notebook is structured to perform data loading, preprocessing, and then various analytical and visualization steps.
3.  **Review Output**: Observe the printed dataframes, plots, and insights generated in the output cells.

## Key Results and Insights
*   The project successfully loaded and preprocessed the Zomato dataset.
*   Visualizations were generated to show the distribution of restaurant types, ratings, and the number of votes per restaurant type.
*   Insights into online order and table booking preferences were derived by restaurant type, providing a clear picture of how these services are adopted across different restaurant categories.

## Libraries Used
*   `pandas`: For data manipulation and analysis.
*   `numpy`: For numerical operations.
*   `matplotlib.pyplot`: For creating static, interactive, and animated visualizations.
*   `seaborn`: For making attractive and informative statistical graphics.
*   `gdown`: For downloading files from Google Drive (if used).

# Task
Analyze and visualize online order and table booking preferences by restaurant type using the `df` DataFrame.

## Analyze Online Order Preferences by Restaurant Type

### Subtask:
Group the DataFrame by 'listed_in(type)' and 'online_order', count the occurrences, and visualize the distribution using a stacked bar chart to show online order preferences for each restaurant type.

**Reasoning**:
I will group the DataFrame by 'listed_in(type)' and 'online_order' to count occurrences, then unstack the result and plot a stacked bar chart to visualize online order preferences across restaurant types.
"""

online_order_counts = df.groupby(['listed_in(type)', 'online_order']).size().unstack(fill_value=0)

online_order_counts.plot(kind='bar', stacked=True, figsize=(10, 6))
plt.title('Online Order Preferences by Restaurant Type')
plt.xlabel('Restaurant Type')
plt.ylabel('Number of Restaurants')
plt.xticks(rotation=45)
plt.legend(title='Online Order')
plt.tight_layout()
plt.show()

"""## Analyze Table Booking Preferences by Restaurant Type

### Subtask:
Group the DataFrame by 'listed_in(type)' and 'book_table', count the occurrences, and visualize the distribution using a stacked bar chart to show table booking preferences for each restaurant type.

## Summary:

### Data Analysis Key Findings

*   The analysis successfully visualized online order preferences across different restaurant types using a stacked bar chart.
*   The visualization clearly shows the distribution of restaurants offering and not offering online ordering for each `listed_in(type)`. (Specific distribution patterns are implied by the chart's generation but not numerically detailed in the provided output).

### Insights or Next Steps

*   Further analysis could quantify the percentage of restaurants offering online orders within each type to identify specific types with high or low adoption rates.
*   Businesses could use these insights to tailor their online ordering strategies, focusing on types with high online order demand or exploring opportunities in underserved restaurant categories.
"""